[package]
name = "rpbcopy"
version = "0.1.0"
edition = "2021"
authors = ["Yunchaun Chen <chenych11@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
clap = { version = "3.1.6", features = ["derive"] }
exitcode = "1.1.2"